#!/bin/bash

#use this script to initiate a Webserver  via AWS EC2 User Data

#install httpd (AWS Linux 2 version)
yum update -y
yum install -y httpd

systemctl start httpd
systemctl enable httpd

echo "<h1>Hello World From $(hostname -f)</h1><h2>Developed by Abdul. </h2><h3>A well rounded Devops Enginer and AWS Solutions Architect</h3>" > /var/www/html/index.html