---
- name: Install Java
  apt:
    name: openjdk-8-jdk
    state: present

- name: Add Jenkins repository key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present

- name: Add Jenkins repository
  apt_repository:
    repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
    state: present

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
