---
- name: Install Kubernetes dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add Kubernetes repository key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes repository
  apt_repository:
    repo: "{{ kubernetes_repo_url }}"
    state: present

- name: Install Kubernetes
  apt:
    name: "{{ kubernetes_package }}"
    state: present